import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
public object Libs {
    /**
     * https://github.com/apollographql/apollo-android/
     */
    public const val apollo_android_support: String =
            "com.apollographql.apollo:apollo-android-support:" + Versions.com_apollographql_apollo

    /**
     * https://github.com/apollographql/apollo-android/
     */
    public const val apollo_coroutines_support: String =
            "com.apollographql.apollo:apollo-coroutines-support:" +
            Versions.com_apollographql_apollo

    /**
     * https://github.com/apollographql/apollo-android/
     */
    public const val apollo_runtime: String = "com.apollographql.apollo:apollo-runtime:" +
            Versions.com_apollographql_apollo

    /**
     * https://github.com/apollographql/apollo-android/
     */
    public const val com_apollographql_apollo_gradle_plugin: String =
            "com.apollographql.apollo:com.apollographql.apollo.gradle.plugin:" +
            Versions.com_apollographql_apollo

    public const val apollo_normalized_cache_sqlite: String =
            "com.apollographql.apollo:apollo-normalized-cache-sqlite:" +
            Versions.com_apollographql_apollo

    public const val databinding_adapters: String = "androidx.databinding:databinding-adapters:" +
            Versions.androidx_databinding

    /**
     * https://developer.android.com/studio
     */
    public const val databinding_common: String = "androidx.databinding:databinding-common:" +
            Versions.androidx_databinding

    /**
     * https://developer.android.com/studio
     */
    public const val databinding_compiler: String = "androidx.databinding:databinding-compiler:" +
            Versions.androidx_databinding

    public const val databinding_runtime: String = "androidx.databinding:databinding-runtime:" +
            Versions.androidx_databinding

    /**
     * https://square.github.io/okhttp/
     */
    public const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.com_squareup_okhttp3

    /**
     * https://square.github.io/okhttp/
     */
    public const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * https://kotlinlang.org/
     */
    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    public const val navigation_fragment_ktx: String =
            "androidx.navigation:navigation-fragment-ktx:" + Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    public const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" + Versions.androidx_navigation

    public const val moshi_gradle: String =
        "com.squareup.moshi:moshi-kotlin:" + Versions.moshi_gradle


    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    public const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/testing
     */
    public const val junit: String = "androidx.test.ext:junit:" + Versions.androidx_test_ext

    /**
     * https://developer.android.com/testing
     */
    public const val junit_ktx: String = "androidx.test.ext:junit-ktx:" + Versions.androidx_test_ext

    public const val koin_android: String = "org.koin:koin-android:" + Versions.org_koin

    public const val koin_androidx_ext: String = "org.koin:koin-androidx-ext:" + Versions.org_koin

    public const val koin_androidx_scope: String = "org.koin:koin-androidx-scope:" +
            Versions.org_koin

    public const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:" +
            Versions.org_koin

    /**
     * https://developer.android.com/studio
     */
    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    public const val androidx_core_core_ktx: String = "androidx.core:core-ktx:" +
            Versions.androidx_core_core_ktx

    /**
     * https://developer.android.com/testing
     */
    public const val androidx_test_core_ktx: String = "androidx.test:core-ktx:" +
            Versions.androidx_test_core_ktx

    /**
     * https://developer.android.com/testing
     */
    public const val androidx_test_runner: String = "androidx.test:runner:" +
            Versions.androidx_test_runner

    /**
     * https://developer.android.com/testing
     */
    public const val androidx_test_rules: String = "androidx.test:rules:" +
            Versions.androidx_test_rules

    /**
     * https://developer.android.com/testing
     */
    public const val androidx_test_core: String = "androidx.test:core:" +
            Versions.androidx_test_core

    public const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" +
            Versions.kotlinx_coroutines_android

    /**
     * http://www.github.com/kotlintest/kotlintest
     */
    public const val kotest: String = "io.kotlintest:kotlintest-runner-junit5:" +
            Versions.kotest

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:" + Versions.kotlinx_coroutines_core

    /**
     * https://developer.android.com/jetpack/androidx
     */
    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:" + Versions.lifecycle_viewmodel_ktx

    /**
     * https://developer.android.com/jetpack/androidx
     */
    public const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:" +
            Versions.lifecycle_livedata_ktx

    /**
     * https://developer.android.com/jetpack/androidx
     */
    public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:" +
            Versions.lifecycle_runtime_ktx

    /**
     * http://tools.android.com
     */
    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * https://developer.android.com/jetpack/androidx
     */
    public const val recyclerview: String = "androidx.recyclerview:recyclerview:" +
            Versions.recyclerview

    /**
     * https://developer.android.com/studio
     */
    public const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" +
            Versions.lint_gradle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    public const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    public const val kaspresso: String = "com.kaspersky.android-components:kaspresso:" +
            Versions.kaspresso

    /**
     * https://github.com/material-components/material-components-android
     */
    public const val material: String = "com.google.android.material:material:" + Versions.material

    public const val multidex: String = "androidx.multidex:multidex:" + Versions.multidex

    public const val avi_loader: String = "com.wang.avi:library:" + Versions.library

    /**
     * https://developer.android.com/studio
     */
    public const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://github.com/coil-kt/coil
     */
    public const val coil: String = "io.coil-kt:coil:" + Versions.coil
}
