import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
public object Versions {
    public const val com_apollographql_apollo: String = "2.5.2"

    public const val androidx_databinding: String = "4.1.2"

    public const val com_squareup_okhttp3: String = "4.9.0" // available: "4.9.1"

    public const val org_jetbrains_kotlin: String = "1.4.21" // available: "1.4.21-2"

    public const val androidx_navigation: String = "2.3.3"
    public const val moshi_gradle: String = "1.11.0"

    public const val androidx_test_ext: String = "1.1.2"

    public const val org_koin: String = "2.2.2"

    public const val com_android_tools_build_gradle: String = "4.1.2"

    public const val androidx_core_core_ktx: String = "1.3.2"

    public const val androidx_test_core_ktx: String = "1.3.0"

    public const val androidx_test_runner: String = "1.3.1-alpha02"

    public const val androidx_test_rules: String = "1.3.1-alpha02"

    public const val androidx_test_core: String = "1.3.0"

    public const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    public const val kotlinx_coroutines_android: String = "1.4.1" // available: "1.4.2"

    public const val kotest: String = "3.4.2"

    public const val kotlinx_coroutines_core: String = "1.3.9" // available: "1.4.2"

    public const val lifecycle_viewmodel_ktx: String = "2.3.0-rc01"

    public const val lifecycle_livedata_ktx: String = "2.2.0"

    public const val lifecycle_runtime_ktx: String = "2.2.0"

    public const val constraintlayout: String = "2.0.4"

    public const val recyclerview: String = "1.1.0"

    public const val lint_gradle: String = "27.1.2"

    public const val appcompat: String = "1.2.0"

    public const val kaspresso: String = "1.2.0"

    public const val material: String = "1.2.1"

    public const val multidex: String = "2.0.1"

    public const val library: String = "2.1.3"

    public const val aapt2: String = "4.1.2-6503028"

    public const val coil: String = "0.11.0" // available: "1.1.1"

    /**
     * Current version: "6.5"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    public const val gradleLatestVersion: String = "6.8.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
public val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
